In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline
from sklearn.datasets import load_digits
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import *

In [40]:
data=load_digits()

In [41]:
x=data.data
y=data.target

In [42]:
x=pd.DataFrame(x)
y=pd.DataFrame(y)

In [43]:
x.head()

0    1    2     3     4     5    6    7    8    9  ...    54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0 ...   5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0 ...   9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [44]:
x.shape,y.shape

((1797, 64), (1797, 1))

In [45]:
x = preprocessing.scale(x)

In [46]:
x

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [47]:
x=pd.DataFrame(x)

In [48]:
pca = PCA(n_components=16)

In [49]:
pca=pca.fit_transform(x)
x = pca

In [50]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2)

In [51]:
modl= LogisticRegression()

In [52]:
modl.fit(X_train,Y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [53]:
pred = modl.predict(X_test)

In [54]:
print("Accuracy Score:\n")
print(metrics.accuracy_score(Y_test,pred)*100)
print("Classification Report\n")
print(classification_report(Y_test,pred))
print("Confusion Matrix")
print(confusion_matrix(Y_test,pred))

Accuracy Score:

92.77777777777779
Classification Report

             precision    recall  f1-score   support

          0       0.97      1.00      0.98        29
          1       0.87      0.92      0.89        37
          2       0.91      0.97      0.94        33
          3       0.97      0.88      0.92        34
          4       0.95      0.95      0.95        38
          5       0.86      0.97      0.91        33
          6       1.00      0.97      0.99        35
          7       0.91      0.97      0.94        40
          8       0.92      0.81      0.86        42
          9       0.94      0.87      0.91        39

avg / total       0.93      0.93      0.93       360

Confusion Matrix
[[29  0  0  0  0  0  0  0  0  0]
 [ 0 34  0  0  0  1  0  0  1  1]
 [ 0  0 32  0  0  0  0  1  0  0]
 [ 0  0  1 30  0  0  0  2  1  0]
 [ 0  0  0  0 36  1  0  0  0  1]
 [ 1  0  0  0  0 32  0  0  0  0]
 [ 0  0  0  0  0  0 34  0  1  0]
 [ 0  0  0  0  1  0  0 39  0  0]
 [ 0  3  2  1  0  1  0